version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - infra
  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    networks:
      - infra

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker_volumes/nginx/certs:/etc/nginx/certs:rw
      - ./docker_volumes/nginx/html:/usr/share/nginx/html:rw
      - ./docker_volumes/nginx/vhost.d:/etc/nginx/vhost.d:rw
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - infra

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    depends_on:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./docker_volumes/nginx/certs:/etc/nginx/certs:rw
      - ./docker_volumes/nginx/vhost.d:/etc/nginx/vhost.d:rw
      - ./docker_volumes/nginx/html:/usr/share/nginx/html:rw
      - ./docker_volumes/acme.sh:/etc/acme.sh
    networks:
      - infra

  host-nginx:
    image: nginx
    container_name: host-nginx
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=a102.mgbg.kr
      - LETSENCRYPT_HOST=a102.mgbg.kr
      - LETSENCRYPT_EMAIL=jmg97@kakao.com
    networks:
      - infra

  jenkins:
    image: jmg97/custom-jenkins:latest
    container_name: jenkins
    environment:
      - VIRTUAL_PORT=8080
      - JENKINS_OPTS="--prefix=/jenkins"
    volumes:
      - ./docker_volumes/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - infra

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ""
    volumes:
      - ./docker_volumes/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - infra

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - infra


networks:
  infra:
    external: true

volumes:
  certs:
    driver: local
    driver_opts:
      type: none
      device: $PWD/docker_volumes/nginx/certs
      o: bind
  vhostd:
    driver: local
    driver_opts:
      type: none
      device: $PWD/docker_volumes/nginx/vhost.d
      o: bind
  html:
    driver: local
    driver_opts:
      type: none
      device: $PWD/docker_volumes/nginx/html
      o: bind
  jenkins_home:
    driver: local
    driver_opts:
      type: none
      device: $PWD/docker_volumes/jenkins
      o: bind
  mysql_data:
    driver: local
    driver_opts:
      type: none
      device: $PWD/docker_volumes/mysql
      o: bind

