spring:
  application:
    name: eureka
  config:
    import: optional:configserver:${CONFIG_IMPORT}
  cloud:
    config:
      discovery:
        enabled: false
  security:
    user:
      name: ${EUREKA_NAME}
      password: ${EUREKA_PASSWORD}
