spring:
  application:
    name: eureka
  config:
    import: "configserver:http://localhost:8888"
  cloud:
    config:
      profile: dev
  security:
    user:
      name: ${EUREKA_NAME}
      password: ${EUREKA_PASSWORD}
logging:
  level:
    org:
      springframework:
        web: DEBUG