spring:
  application:
    name: eureka
  config:
    import: ${CONFIG_IMPORT}
  cloud:
    config:
      discovery:
        enabled: false
        service-id: configserver
      fail-fast: false
  security:
    user:
      name: ${EUREKA_NAME}
      password: ${EUREKA_PASSWORD}
