spring:
  application:
    name: gateway
  config:
    import: "configserver:http://localhost:8888"
  cloud:
    config:
      profile: dev

logging:
  level:
    org:
      springframework:
        cloud: DEBUG
        web: DEBUG