spring:
  application:
    name: gateway
  config:
    import: optional:configserver:${CONFIG_IMPORT}
  cloud:
    config:
      profile: dev

logging:
  level:
    org:
      springframework:
        cloud: DEBUG
        web: DEBUG