spring:
  application:
    name: user-service
  config:
    import: "configserver:http://localhost:8888"
  cloud:
    config:
      profile: dev
  profiles:
    include: oauth
fcm:
  service-account-file: key/mealtoyou.json
  topic-name: testMessage
  project-id: mealtoyou-197d9