spring:
  application:
    name: food-service
  config:
    import: optional:configserver:${CONFIG_IMPORT}
  cloud:
    config:
      profile: dev
  data:
    elasticsearch:
      repositories:
        enabled: true
      url: localhost:9200